/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'customerName' : string,
  'finalTotal' : number,
  'labourCost' : number,
  'powderCost' : number,
  'number' : bigint,
  'timestamp' : Time,
  'taxAmount' : number,
  'gasCost' : number,
  'subtotal' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getTotalBillCount' : ActorMethod<[], bigint>,
  'getTotalSalesAmount' : ActorMethod<[], number>,
  'saveBill' : ActorMethod<[string, number, number, number, number], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];