/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Bill = IDL.Record({
  'customerName' : IDL.Text,
  'finalTotal' : IDL.Float64,
  'labourCost' : IDL.Float64,
  'powderCost' : IDL.Float64,
  'number' : IDL.Nat,
  'timestamp' : Time,
  'taxAmount' : IDL.Float64,
  'gasCost' : IDL.Float64,
  'subtotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getTotalBillCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalSalesAmount' : IDL.Func([], [IDL.Float64], ['query']),
  'saveBill' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Bill = IDL.Record({
    'customerName' : IDL.Text,
    'finalTotal' : IDL.Float64,
    'labourCost' : IDL.Float64,
    'powderCost' : IDL.Float64,
    'number' : IDL.Nat,
    'timestamp' : Time,
    'taxAmount' : IDL.Float64,
    'gasCost' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getTotalBillCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalSalesAmount' : IDL.Func([], [IDL.Float64], ['query']),
    'saveBill' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };